### ISSUE TITLE
First loop to Floopr

### ISSUE THREAD

**Issue by Chriffe** [Jontes-Tech/floopr#1]
Great work! Here comes a hiphop drum loop I made.

Suggestion on what information the metadata should contain:

Key: none
Tempo: 90 bpm
Instrument: Drums
Genre: Hip hop
Type: Audio

I also suggest the folder structure should be something like: /content/instrument/hiphop/
So instrument first and then genre. Makes it easier for people to find everything in one group of instruments.

[hiphop-beat1.mp3.zip](https://github.com/Jontes-Tech/floopr/files/10034557/hiphop-beat1.mp3.zip)

**Comment by Jontes-Tech** [comment]
Actually I am considering doing only the instrument (example: /content/drums) and then just put the genre in the metadata.

**Comment by Chriffe** [comment]
Yeah, that is probably a smarter way to do it!

Btw, consider adding creators name in the metadata. And you should probably add something about the license (public domain?) in the readme file.

**Comment by Jontes-Tech** [comment]
I am already adding creator's name in the metadata, referring to users by their GitHub username currently ("Chriffe" for you). I am comparing different licenses, I am considering GNU LGPL for the code and Creative Commons 0 (basically public domain without the legalwork) for the loops! Let me know if you have any objections.

**Comment by Jontes-Tech** [comment]
Oh, and also, rather unrelated but please accept my collaborator request.

**Comment by Chriffe** [comment]
Sounds great!

Request accepted :)
