### ISSUE TITLE
Logo / Favicon needed?

### ISSUE THREAD

**Issue by Jontes-Tech** [Jontes-Tech/floopr#2]
I believe having a logo would be quite awesome!

**Comment by Chriffe** [comment]
Here is a suggestion for how it could look. I do not know anything about designing logos, but I like the idea of replacing the two O:s with the infinity symbol. The logo should be a vector file, but I have not learned Inkscape yet, so this is the best I could do.

![floopr-suggested-logo](https://user-images.githubusercontent.com/102315726/202787374-cda6808a-0843-4c09-90e0-8f40a9211240.png)

**Comment by Jontes-Tech** [comment]
Dude, this is awesome! However, we would also need a version suitable for the favicon (the icon displayed in the tab). That version would need to look good even when tiny.

**Comment by Jontes-Tech** [comment]
Actually I am considering rebranding to freeloopr to emphasise the fact that it's free as in speech. Which name do you prefer?

**Comment by Chriffe** [comment]
I really like the name Floopr. It is short and rolls off your tounge. I think the fact that it is free is apparent enough.

**Comment by Chriffe** [comment]
I do not know about this one... creating an icon is really hard. But I tried to use the font and symbol from my logo suggestion to create something compact.

![favicon-suggest](https://user-images.githubusercontent.com/102315726/202806804-ac70398d-d9c4-4cf8-b8d7-18d5b8747ea7.png)

**Comment by Jontes-Tech** [comment]
Loving it! Will be adding some the primary theme color to the svgs if you don't mind.

**Comment by Chriffe** [comment]
Yeah do what ever you want with it :)

**Comment by Jontes-Tech** [comment]
Oh, these seem to be PNGs tho...

**Comment by Chriffe** [comment]
Yeah as I wrote, I have not learned Inkscape enough yet.

**Comment by Jontes-Tech** [comment]
Oh, so you didn't make these in Inkscape? If you did you should just be able to send me the save files and I'll make it an SVG

**Comment by Chriffe** [comment]
Used an online converter. Have a look at them and see if they work now. I am on my phone, so it is hard for me to have a closer look. But at a quick glance it looks like the conversion looks fine.

![202806804-ac70398d-d9c4-4cf8-b8d7-18d5b8747ea7](https://user-images.githubusercontent.com/102315726/202846958-5f3454cb-0f37-4789-bb30-04d301b2d8ff.svg)
![202787374-cda6808a-0843-4c09-90e0-8f40a9211240](https://user-images.githubusercontent.com/102315726/202846960-5110562e-7453-450a-aab8-452547616ccb.svg)

**Comment by Jontes-Tech** [comment]
Closing as completed
