### ISSUE TITLE
Domain name?

### ISSUE THREAD

**Issue by Jontes-Tech** [Jontes-Tech/floopr#3]
We did it! Floopr is now up and running on a temporary domain (floopr.jontes.page)! But now we need to look at domain names.

I am thinking one of [these](https://porkbun.com/checkout/search?q=floopr).

Maybe floopr.org or floopr.xyz?

Who is going to pay for domain costs?

What do you think @Chriffe?

**Comment by Chriffe** [comment]
I have bought floopr.org

We can set everything up with the domain tomorrow of if we meet irl :)

**Comment by Jontes-Tech** [comment]
Awesome! Thanks for doing that for the project.

**Comment by Jontes-Tech** [comment]
Deployed to floopr.org. Working on minor patches for lightmode users and implementing the sorted by date feature.

**Comment by Jontes-Tech** [comment]
Closing as completed
