### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Chriffe** [Jontes-Tech/floopr#4]
I have som suggestions with the design of the site:

1. Remove the "Welcome to Floopr" and replace it with the logo.
2. Move the "Instruments" from the mainpage to its own page.
3. Maybe include a "Recently added" on the mainpage. It should update itself based on what loops has been recently added. I do not know if it is possible, but it would be really cool.
4. A page that explains how to add loops to the project. I am willing to make a video in the future that explains the process of how to make a loop and how to upload it, but for now text works fine.

Also... maybe make the logo black that shows in the readme.md.

**Comment by Jontes-Tech** [comment]
1. Fixed
2. Fixed
3. Would need addeddate in metadata, but technically possible. Considering.
4. That is in the readme, I just copypasted it into the actual site as well.
Also fixed the readme logo.

**Comment by Jontes-Tech** [comment]
Now dark theme readme is broken, working on a fix.

**Comment by Chriffe** [comment]
Great :) Maybe we should rename the instruments page to "Loops"?

I will start making pull requests myself soon. Just need to get everything setup.

**Comment by Jontes-Tech** [comment]
You, since you are a collaborator, does not need to make PRs. You have write access,  so you can just upload right away. Additionally, you can use GitHub desktop to have this github repo as a folder on your computer so you can easily add loops in bulk.

**Comment by Chriffe** [comment]
Yeah I figured all of that out after I posted. :) I have tweaked the guide on how to contribute. Forgot to leave comments. Changed "hminor" to "b-minor". The reason is that "H" is an old way of naming "B" in Sweden and Germany. But hardly no one is using that anymore.

**Comment by Jontes-Tech** [comment]
Oh, I got conflicting information online. It feels good that I returned the favor of rickrolling :)
Now, everything is basically done.
