### ISSUE TITLE
Time signatur to metadata

### ISSUE THREAD

**Issue by Chriffe** [Jontes-Tech/floopr#6]
We need to add time signature to the metadata. The one loop we have now is 4/4. Should not be written out as "44", but rather "4-4" if 4/4 does not work.

**Comment by Chriffe** [comment]
Yeah I think i broke something... Wanted to remove the "s" behind "tempos", "keys", "timesigs" and now all that information disappeared.

**Comment by Jontes-Tech** [comment]
Mhm, you broke it. And that is fine. I should have found a less hacky solution to the problem. Basically it is plural in the url and is therefore plural in the metadata.

**Comment by Jontes-Tech** [comment]
I could on second thought change that.

**Comment by Jontes-Tech** [comment]
Will fix asap.

**Comment by Jontes-Tech** [comment]
Fixed and pushed to prod

**Comment by Jontes-Tech** [comment]
Looking into making 4-4 show up as 4/4 everywhere but the URL.

**Comment by Jontes-Tech** [comment]
We could use "%2F" in the url as it is the official url encoded / for URLs. Looking into this.

**Comment by Jontes-Tech** [comment]
Eh not you type 4SLASH4 to make it be 4/4, good enough.
